### ISSUE TITLE
Issue importing from Day One Classic

### ISSUE THREAD

**Issue by djmbritt** [vonProteus/do2en#1]
Hi there,

Thanks for your script, it was really useful.
But I did have issues reading the dayone.journal file.

I had to remove the getSource() function from do2en.py at line 301.
And replace it with my own string.
I am thinking it has to do with Day One Classic using old formatting.

After i fixed that, everything worked fine.

**Comment by vonProteus** [comment]
can you provide me with your journal or just the entry which cause error?
my journal convert just fine 
but without [301](https://github.com/vonProteus/do2en/blob/master/script/do2en.py#L301) you don't lose any important data

**Comment by djmbritt** [comment]
I assumed you wrote the script for Day One 2.

Here is the error:
Traceback (most recent call last):
  File "script/do2en.py", line 436, in <module>
    obj.main(sys.argv[1:])
  File "script/do2en.py", line 57, in main
    self.saveOutFile()
  File "script/do2en.py", line 234, in saveOutFile
    note = self.makeNote(doe)
  File "script/do2en.py", line 250, in makeNote
    note += self.makeAttributes(doe)
  File "script/do2en.py", line 301, in makeAttributes
    attributes = "\t\t\t<source>"+doe.getSource()+"</source>\n"
  File "/Users/davidbritt/Desktop/do2en/script/doentry.py", line 63, in getSource
    return self.plist["Creator"]["Software Agent"]
KeyError: 'Creator'

This is what I had to change to get it to work.

do2en.py, line 300:
...
    def makeAttributes(self,doe):
        attributes = "\t\t\t<source>"+ "My Name" +"</source>\n"
        attributes += "\t\t\t<reminder-order>0</reminder-order>\n"
...

doentry.py, line 62:
...
    def getSource(self):
       return self.plist["key"]
...

**Comment by vonProteus** [comment]
this script is for Day One Classic (v1)
could you test it and close if it fix your problem?

**Comment by vonProteus** [comment]
no response, closing
